name: Selenium Tests

on: [push]

jobs:
  selenium:
    runs-on: ubuntu-latest
    
    services:
      selenium-hub:
        image: selenium/hub
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome
        ports:
          - 5900:5900
        env:
          - HUB_HOST=selenium-hub
        depends_on:
          - selenium-hub
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -n auto
